[package]
name = "playground-rs"
version = "0.1.0"
authors = ["vladimir"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
strsim = "0.9.3"
rayon = "1.3.0"
